version: '3.8'

services:
  app:
    build: .
    image: kan-ilani-olusturma-asistani-api:latest
    container_name: kan-ilani-olusturma-asistani-api
    ports:
      - "3000:3000"
    volumes:
      - counter-data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  counter-data:
    driver: local